### ISSUE TITLE
Bind exception when starting new nodes

### ISSUE THREAD

**Issue by naderghanbari** [typesafehub/ReactiveMaps#34]
Starting a new node on the akka cluster does not work for me as explained in the tutorial.

I run the following command

```
> activator \
  -Dakka.remote.netty.tcp.port=0 \
  -Dakka.cluster.seed-nodes.1="akka.tcp://application@127.0.0.1:2552" \
  -Dakka.cluster.roles.1=backend-region \
  "run-main backend.Main"
```

but I get a `akka.remote.RemoteTransportException` due to a `java.net.BindException: Address already in use` exception.

Seems that the system property is not being picked at the right time because editing the configuration file manually works. 

I mean when I set `akka.remote.nettey.tcp.port=0` in `application.conf` everything works properly. (I did this obviously for the second node only).

By the way, I'm on Mac OS `v10.11.1` and Java version `1.8.0_66`

**Comment by naderghanbari** [comment]
Here is the exception when I get by running 


```
background log: info: Running backend.Main 
background log: info: [INFO] [11/07/2015 19:30:39.776] [main] [Remoting] Starting remoting
background log: info: [ERROR] [11/07/2015 19:30:39.892] [application-akka.remote.default-remote-dispatcher-6] [NettyTransport(akka://application)] failed to bind to /127.0.0.1:2552, shutting down Netty transport
background log: info: [ERROR] [11/07/2015 19:30:39.898] [main] [Remoting] Remoting error: [Startup failed] [
background log: info: akka.remote.RemoteTransportException: Startup failed
background log: info: 	at akka.remote.Remoting.akka$remote$Remoting$$notifyError(Remoting.scala:135)
background log: info: 	at akka.remote.Remoting.start(Remoting.scala:200)
background log: info: 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:184)
background log: info: 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:58)
background log: info: 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:620)
background log: error: Exception in thread "main" org.jboss.netty.channel.ChannelException: Failed to bind to: /127.0.0.1:2552
background log: info: 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:617)
background log: info: 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:617)
background log: info: 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:634)
background log: info: 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
background log: info: 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
background log: info: 	at backend.Main$.main(Main.scala:27)
background log: info: 	at backend.Main.main(Main.scala)
background log: info: Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /127.0.0.1:2552
background log: info: 	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
background log: info: 	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:410)
background log: error: 	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
background log: error: 	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:410)
background log: error: 	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:406)
background log: error: 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
background log: error: 	at scala.util.Try$.apply(Try.scala:192)
background log: error: 	at scala.util.Success.map(Try.scala:237)
background log: error: 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
background log: error: 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
background log: error: 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
background log: error: 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
background log: error: 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
background log: error: 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
background log: error: 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
background log: error: 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
background log: error: 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
background log: error: 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
background log: error: 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
background log: error: Caused by: java.net.BindException: Address already in use
background log: error: 	at sun.nio.ch.Net.bind0(Native Method)
background log: error: 	at sun.nio.ch.Net.bind(Net.java:433)
background log: error: 	at sun.nio.ch.Net.bind(Net.java:425)
background log: error: 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
background log: error: 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
background log: error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
background log: error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
background log: error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
background log: error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
background log: error: 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
background log: error: 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
background log: error: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
background log: error: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
background log: error: 	at java.lang.Thread.run(Thread.java:745)
background log: info: 	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:406)
background log: info: 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
background log: info: 	at scala.util.Try$.apply(Try.scala:192)
background log: info: 	at scala.util.Success.map(Try.scala:237)
background log: info: 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
background log: info: 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
background log: info: 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
background log: info: 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
background log: info: 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
background log: info: 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
background log: info: 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
background log: info: 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
background log: info: 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
background log: info: 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
background log: info: 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
background log: info: 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
background log: info: 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
background log: info: 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
background log: info: 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
background log: info: Caused by: java.net.BindException: Address already in use
background log: info: 	at sun.nio.ch.Net.bind0(Native Method)
background log: info: 	at sun.nio.ch.Net.bind(Net.java:433)
background log: info: 	at sun.nio.ch.Net.bind(Net.java:425)
background log: info: 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
background log: info: 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
background log: info: 	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
background log: info: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
background log: info: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
background log: info: 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
background log: info: 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
background log: info: 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
background log: info: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
background log: info: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
background log: info: 	at java.lang.Thread.run(Thread.java:745)
background log: info: ]
background log: info: [INFO] [11/07/2015 19:30:39.903] [application-akka.remote.default-remote-dispatcher-5] [akka://application/system/remoting-terminator] Shutting down remote daemon.
background log: info: [INFO] [11/07/2015 19:30:39.906] [application-akka.remote.default-remote-dispatcher-5] [akka://application/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
background log: info: [ERROR] [11/07/2015 19:30:39.909] [application-akka.remote.default-remote-dispatcher-6] [Remoting] Remoting system has been terminated abrubtly. Attempting to shut down transports
background log: info: [INFO] [11/07/2015 19:30:39.911] [ForkJoinPool-3-worker-15] [Remoting] Remoting shut down
background log: info: [INFO] [11/07/2015 19:30:39.911] [application-akka.remote.default-remote-dispatcher-6] [akka://application/system/remoting-terminator] Remoting shut down.
Exception in thread "sbt-bg-threads-1" java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1966)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1966)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:1966)
	at sbt.package$.toError(package.scala:4)
	at sbt.plugins.BackgroundRun$$$$b4c18989468ecd5aa4b4422d7494c6$$$$onfun$apply$6.apply(BackgroundRunPlugin.scala:38)
	at sbt.plugins.BackgroundRun$$$$b4c18989468ecd5aa4b4422d7494c6$$$$onfun$apply$6.apply(BackgroundRunPlugin.scala:37)
	at sbt.BackgroundThreadPool$$anonfun$1.apply$mcV$sp(AbstractBackgroundJobService.scala:134)
	at sbt.BackgroundThreadPool$BackgroundRunnable.run(AbstractBackgroundJobService.scala:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by naderghanbari** [comment]
By the way I tried using and env var instead by putting the following

```
  remote.netty.tcp {
    hostname = "127.0.0.1"
    port = 2552
    port = ${AKKA_TCP_PORT}
  }
```

and setting an env var for the new process (new node) and it works. Just thought that this might help narrowing down the problem.

**Comment by nhooey** [comment]
I'm also having this problem and have to set the port manually in `application.conf`.

**Comment by storytime** [comment]
do you fix this error?
